// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_ZcvWXhehRhko9JBV0NZZH7vD3mkHs0',
    appId: '1:911164975994:android:98f0f1a3c547629f4a84c3',
    messagingSenderId: '911164975994',
    projectId: 'padel-3a8cb',
    storageBucket: 'padel-3a8cb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_QG7SB7nNH4JqyV5rv_zKewbwqxiYxQI',
    appId: '1:911164975994:ios:555b69111efe2e744a84c3',
    messagingSenderId: '911164975994',
    projectId: 'padel-3a8cb',
    storageBucket: 'padel-3a8cb.firebasestorage.app',
    androidClientId: '911164975994-4fbtbii7u9pj5tavo3cnqtjdoc9tc8oo.apps.googleusercontent.com',
    iosClientId: '911164975994-9atool2ig6m2loepo65p9a8phcso5g4b.apps.googleusercontent.com',
    iosBundleId: 'com.padel.hamza',
  );
}
